import type { Metadata } from "next";

import "./globals.css";
import Sidebar from "@/components/Sidebar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex items-start justify-between`}
      >
        <Sidebar/>
        <main className="w-full h-full">
         {children}
        </main>
        
      </body>
    </html>
  );
}
