import type { Metadata } from "next";

import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header"; 



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex items-start justify-between`}>
          <div className="hidden lg:flex min-w-[300px]  border-r min-h-screen ">
           <Sidebar/>   
          </div>
        <main className="grid w-full h-full ">
          <Header/>
         <div className="p-4">
          {children}
         </div>
        </main>
        
      </body>
    </html>
  );
}
